language: node_js 
node_js:
  - 15
cache:
  directories:
  - node_modules 
script:
  - npm run build 
  - touch public/.nojekyll
deploy:
  provider: pages 
  skip_cleanup: true 
  github_token: $GH_TOKEN
  local_dir: public
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master)$